version: "3"

services:
    bot:
        build: .
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            DEV: ${DEV}

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data

volumes:
    mongo-data:
